// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ServiceActor
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using ServiceActor;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServiceActorWrapperTemplate : ServiceActorWrapperTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Linq;\r\nusing System.Threading;\r\nusing System.Threadin" +
                    "g.Tasks;\r\nusing ServiceActor;\r\n\r\npublic class ");
            
            #line 14 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeToWrapName));
            
            #line default
            #line hidden
            this.Write("AsyncActorWrapper : ");
            
            #line 14 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeToWrapFullName));
            
            #line default
            #line hidden
            this.Write(", ServiceActor.IServiceActorWrapper\r\n{\r\n    private readonly ");
            
            #line 16 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeToWrapFullName));
            
            #line default
            #line hidden
            this.Write(" _objectToWrap;\r\n    private readonly string _typeOfObjectToWrap;\r\n\r\n    public o" +
                    "bject WrappedObject { get => _objectToWrap; }\r\n    public ActionQueue ActionQueu" +
                    "e { get; }\r\n\r\n    public ");
            
            #line 22 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeToWrapName));
            
            #line default
            #line hidden
            this.Write("AsyncActorWrapper(");
            
            #line 22 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeToWrapFullName));
            
            #line default
            #line hidden
            this.Write(@" objectToWrap, string typeOfObjectToWrap, ServiceActor.ActionQueue actionQueue)
    {
        _objectToWrap = objectToWrap ?? throw new ArgumentNullException(nameof(objectToWrap));
        _typeOfObjectToWrap = typeOfObjectToWrap ?? throw new ArgumentNullException(nameof(typeOfObjectToWrap));
        ActionQueue = actionQueue ?? throw new ArgumentNullException(nameof(actionQueue));
    }

    ");
            
            #line 29 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 foreach (var property in GetProperties()) { 
            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 30 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        ");
            
            #line 32 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (property.CanRead) { 
            
            #line default
            #line hidden
            this.Write("        get\r\n        {\r\n            ");
            
            #line 35 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(property.GetAccessor)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            return _objectToWrap.");
            
            #line 37 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 39 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 41 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(" res = default;\r\n            Exception exceptionThrown = null;\r\n            var c" +
                    "allContext = CallContext.GetOrCreateCurrent();\r\n            if (!callContext.Can" +
                    "Push(ActionQueue, ");
            
            #line 44 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(property.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n            {\r\n                return _objectToWrap.");
            
            #line 46 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(@";
            }
            var invocationItem = ActionQueue.Enqueue(this, _typeOfObjectToWrap, () =>
            {
                try
                {
                    CallContext.SetCurrent(callContext);
                    callContext.Push(ActionQueue);
                    res = _objectToWrap.");
            
            #line 54 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n                }\r\n                catch (Exception ex)\r\n                {\r\n  " +
                    "                  exceptionThrown = ex;\r\n                }\r\n\r\n                ca" +
                    "llContext.Pop(ActionQueue);\r\n\r\n            }, \r\n            keepContextForAsyncC" +
                    "alls: ");
            
            #line 64 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(property.GetAccessor) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(@");

            invocationItem?.WaitExecuted();

            if (exceptionThrown != null)
                throw exceptionThrown;

            if (invocationItem != null && invocationItem.WaitForPendingOperationCompletion())
            {
                res = invocationItem.GetLastPendingOperationResult<");
            
            #line 73 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(">();\r\n            }\r\n\r\n            return res;\r\n\r\n            ");
            
            #line 78 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n        ");
            
            #line 80 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 81 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (property.CanWrite) { 
            
            #line default
            #line hidden
            this.Write("        set\r\n        {\r\n            ");
            
            #line 84 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(property.SetAccessor)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            _objectToWrap.");
            
            #line 86 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\r\n            ");
            
            #line 88 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n                var callContext = CallContext.GetOrCreateCurrent();\r\n          " +
                    "      if (!callContext.CanPush(ActionQueue, ");
            
            #line 91 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(property.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    _objectToWrap.");
            
            #line 93 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n                    return;\r\n                }\r\n\r\n                ");
            
            #line 97 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(property.SetAccessor)) { 
            
            #line default
            #line hidden
            this.Write("                Exception exceptionThrown = null;\r\n                ");
            
            #line 99 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                var invocationItem = ActionQueue.Enqueue(this, _typeOfObjectToWra" +
                    "p, () =>\r\n                {\r\n                    CallContext.SetCurrent(callCont" +
                    "ext);\r\n                    callContext.Push(ActionQueue);\r\n                    ");
            
            #line 104 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(property.SetAccessor)) { 
            
            #line default
            #line hidden
            this.Write("                    try\r\n                    {\r\n                        _objectTo" +
                    "Wrap.");
            
            #line 107 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n                    }\r\n                    catch (Exception ex)\r\n     " +
                    "               {\r\n                        exceptionThrown = ex;\r\n               " +
                    "     }\r\n\r\n                    callContext.Pop(ActionQueue);\r\n                   " +
                    " ");
            
            #line 115 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    try\r\n                    {\r\n                        _objectTo" +
                    "Wrap.");
            
            #line 118 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n                    }\r\n                    finally\r\n                  " +
                    "  {\r\n                        callContext.Pop(ActionQueue);\r\n                    " +
                    "}\r\n                    ");
            
            #line 124 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                }, \r\n                keepContextForAsyncCalls: ");
            
            #line 126 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(property.SetAccessor) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(",\r\n                blockingCaller: ");
            
            #line 127 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BlockCaller(property.SetAccessor) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                ");
            
            #line 129 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(property.SetAccessor)) { 
            
            #line default
            #line hidden
            this.Write("                invocationItem?.WaitExecuted();\r\n\r\n                if (exceptionT" +
                    "hrown != null)\r\n                    throw exceptionThrown;\r\n\r\n                in" +
                    "vocationItem?.WaitForPendingOperationCompletion();\r\n                ");
            
            #line 136 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            ");
            
            #line 139 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n        ");
            
            #line 141 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n\t");
            
            #line 143 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 145 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 foreach (var method in GetMethods()) { 
            
            #line default
            #line hidden
            this.Write("    \r\n        ");
            
            #line 147 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (method.Info.ReturnType == typeof(void)) { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 148 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodDeclarationCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 150 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(method)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            _objectToWrap.");
            
            #line 152 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 154 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n                var callContext = CallContext.GetOrCreateCurrent();\r\n          " +
                    "      if (!callContext.CanPush(ActionQueue, ");
            
            #line 157 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(method.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    _objectToWrap.");
            
            #line 159 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n                    return;\r\n                }\r\n\r\n                ");
            
            #line 163 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(method)) { 
            
            #line default
            #line hidden
            this.Write("                Exception exceptionThrown = null;\r\n                ");
            
            #line 165 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                var invocationItem = ActionQueue.Enqueue(this, _typeOfObjectToW" +
                    "rap, () =>\r\n                {\r\n                    CallContext.SetCurrent(callCo" +
                    "ntext);\r\n                    callContext.Push(ActionQueue);\r\n                   " +
                    " ");
            
            #line 171 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(method)) { 
            
            #line default
            #line hidden
            this.Write("                    try\r\n                    {\r\n                        _objectTo" +
                    "Wrap.");
            
            #line 174 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(@";
                    }
                    catch (Exception ex)
                    {
                        exceptionThrown = ex;
                    }
                    
                    callContext.Pop(ActionQueue);

                    ");
            
            #line 183 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    try\r\n                    {\r\n                        _objectTo" +
                    "Wrap.");
            
            #line 186 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n                    }\r\n                    finally\r\n                    {\r\n   " +
                    "                     callContext.Pop(ActionQueue);\r\n                    }\r\n     " +
                    "               ");
            
            #line 192 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                }, \r\n                keepContextForAsyncCalls: ");
            
            #line 194 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(method) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(",\r\n                blockingCaller: ");
            
            #line 195 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BlockCaller(method) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(" );\r\n\r\n                ");
            
            #line 197 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (BlockCaller(method)) { 
            
            #line default
            #line hidden
            this.Write("                invocationItem?.WaitExecuted();\r\n\r\n                if (exceptionT" +
                    "hrown != null)\r\n                    throw exceptionThrown;\r\n\r\n                in" +
                    "vocationItem?.WaitForPendingOperationCompletion();\r\n                ");
            
            #line 204 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            ");
            
            #line 207 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n        ");
            
            #line 209 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else if (method.Info.ReturnType == typeof(Task)) { 
            
            #line default
            #line hidden
            this.Write("        public async ");
            
            #line 210 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodDeclarationCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 212 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(method)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            await _objectToWrap.");
            
            #line 214 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 216 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n            Exception exceptionThrown = null;\r\n            var callContext = Ca" +
                    "llContext.GetOrCreateCurrent();\r\n            if (!callContext.CanPush(ActionQueu" +
                    "e, ");
            
            #line 220 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(method.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n            {\r\n                await _objectToWrap.");
            
            #line 222 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(@";
                return;
            }

            var invocationItem = ActionQueue.EnqueueAsync(this, _typeOfObjectToWrap, async () =>
            {
                CallContext.SetCurrent(callContext);
                callContext.Push(ActionQueue);

                try
                {
                    await _objectToWrap.");
            
            #line 233 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n                }\r\n                catch (Exception ex)\r\n                {\r\n  " +
                    "                  exceptionThrown = ex;\r\n                }\r\n\r\n                ca" +
                    "llContext.Pop(ActionQueue);\r\n            }, \r\n            keepContextForAsyncCal" +
                    "ls: ");
            
            #line 242 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(method) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(@");

			if (invocationItem != null)
            {
				await invocationItem.WaitExecutedAsync();
			}

            if (exceptionThrown != null)
                throw exceptionThrown;

            if (invocationItem != null)
			{
				await invocationItem.WaitForPendingOperationCompletionAsync();
			}

            ");
            
            #line 257 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n        ");
            
            #line 260 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else if (method.Info.ReturnType.BaseType == typeof(Task)) { 
            
            #line default
            #line hidden
            this.Write("        public async ");
            
            #line 261 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodDeclarationCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 263 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(method)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            return await _objectToWrap.");
            
            #line 265 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 267 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 269 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.ReturnType.GetGenericArguments()[0].GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(" res = default;\r\n            \r\n            Exception exceptionThrown = null;\r\n   " +
                    "         var callContext = CallContext.GetOrCreateCurrent();\r\n\r\n            if (" +
                    "!callContext.CanPush(ActionQueue, ");
            
            #line 274 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(method.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n            {\r\n                return await _objectToWrap.");
            
            #line 276 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(@";
            }

            var invocationItem = ActionQueue.EnqueueAsync(this, _typeOfObjectToWrap, async () =>
            {
                CallContext.SetCurrent(callContext);
                callContext.Push(ActionQueue);

                try
                {
                    res = await _objectToWrap.");
            
            #line 286 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n                }\r\n                catch (Exception ex)\r\n                {\r\n  " +
                    "                  exceptionThrown = ex;\r\n                }\r\n\r\n                ca" +
                    "llContext.Pop(ActionQueue);\r\n            }, \r\n            keepContextForAsyncCal" +
                    "ls: ");
            
            #line 295 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(method) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(@");

			if (invocationItem != null)
            {
				await invocationItem.WaitExecutedAsync();
			}

            if (exceptionThrown != null)
                throw exceptionThrown;

            if (invocationItem != null && (await invocationItem.WaitForPendingOperationCompletionAsync()))
            {
                res = invocationItem.GetLastPendingOperationResult<");
            
            #line 307 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.ReturnType.GetGenericArguments()[0].GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(">();\r\n            }\r\n\r\n            return res;\r\n\r\n            ");
            
            #line 312 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n        ");
            
            #line 314 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 315 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodDeclarationCode()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            ");
            
            #line 317 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 if (MethodAllowsConcurrentAccess(method)) { 
            
            #line default
            #line hidden
            this.Write("\r\n            return _objectToWrap.");
            
            #line 319 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n            ");
            
            #line 321 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 323 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.ReturnType.GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(" res = default;\r\n            Exception exceptionThrown = null;\r\n            var c" +
                    "allContext = CallContext.GetOrCreateCurrent();\r\n            if (!callContext.Can" +
                    "Push(ActionQueue, ");
            
            #line 326 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AllowReentrantCalls(method.InterfaceType)));
            
            #line default
            #line hidden
            this.Write("))\r\n            {\r\n                return _objectToWrap.");
            
            #line 328 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(@";
            }

            var invocationItem = ActionQueue.Enqueue(this, _typeOfObjectToWrap, () =>
            {
                try
                {
                    CallContext.SetCurrent(callContext);
                    callContext.Push(ActionQueue);
                    res = _objectToWrap.");
            
            #line 337 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.GetMethodInvocationCode()));
            
            #line default
            #line hidden
            this.Write(";\r\n                }\r\n                catch (Exception ex)\r\n                {\r\n  " +
                    "                  exceptionThrown = ex;\r\n                }\r\n\r\n                ca" +
                    "llContext.Pop(ActionQueue);\r\n\r\n            }, \r\n            keepContextForAsyncC" +
                    "alls: ");
            
            #line 347 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeepAsyncContext(method) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(@");

            invocationItem?.WaitExecuted();

            if (exceptionThrown != null)
                throw exceptionThrown;

            if (invocationItem != null && invocationItem.WaitForPendingOperationCompletion())
            {
                res = invocationItem.GetLastPendingOperationResult<");
            
            #line 356 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Info.ReturnType.GetTypeReferenceCode()));
            
            #line default
            #line hidden
            this.Write(">();\r\n            }\r\n\r\n            return res;\r\n\r\n            ");
            
            #line 361 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n        ");
            
            #line 364 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 366 "D:\Source\Projects\ServiceActor\src\ServiceActor\ServiceActorWrapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    \r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ServiceActorWrapperTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
